<?php
require('../fpdf/fpdf.php');
include "../functions.php";
require "../conversor.php";
conexion("localhost","root","danae","evya");
$contrato=$_GET['sContrato'];
$Pedido=$_GET['iFolioPedido'];
$req=$_GET['iFolioRequisicion'];
$qry=consulta("*","anexo_ppedido","iFolioPedido=".$Pedido." and sContrato='".$contrato."'");
class PDF extends FPDF
{
//Cabecera de página
function FancyTable($header,$data,$num_rows)
{
	//Colores, ancho de línea y fuente en negrita
	$this->SetFillColor(0,0,255);
	$this->SetTextColor(255);
	$this->SetDrawColor(0,0,0);
	$this->SetLineWidth(.1);
	$this->SetFont('Arial','B',8);
	//Cabecera
	$w=array('15','15','20','35','20','20','155');
	//Restauración de colores y fuentes
	$this->SetFillColor(225,225,225);
	$this->SetTextColor(80);
	//Datos
	$fill=false;
	$j=-1;
	for($i=1;$i<=$num_rows;$i++)
	{
		$this->SetFont('Arial','I',8);
		$this->Cell($w[0],4,$data[$j++],"T",0,'C',$fill);
		$this->Cell($w[1],4,$data[$j++],"T",0,'C',$fill);
		$this->Cell($w[2],4,$data[$j++],"T",0,'C',$fill);
		$this->Cell($w[3],4,$data[$j++],"T",0,'L',$fill);
		$this->Cell($w[4],4,$data[$j++],"T",0,'R',$fill);
		$this->Cell($w[5],4,$data[$j++],"T",0,'R',$fill);	
		$this->SetFont('Arial','I',7.5);
		$this->Multicell($w[6],4,$data[$j++],"T","L",$fill);
//		$this->Ln();
		$fill=!$fill;
	}
	$this->Cell(280,0,'','T');
}
function Header()
{
    //Logo
$contrato=$_GET['sContrato'];
$Pedido=$_GET['iFolioPedido'];
$req=$_GET['iFolioRequisicion'];
	$qry_head=consulta("*","configuracion","sContrato='".$contrato."'");
    //Arial bold 15
    $this->SetFont('Helvetica','B',14);
	$this->SetDrawColor(0,100,0);
	$this->SetLineWidth(.4);
    //Movernos a la derecha
    $this->Cell(40,20,"","LT");
    //Título
	while($rowh=mysql_fetch_array($qry_head)){
	    $this->Image('images/compania.jpg',17,15,32);
		$this->SetTextColor(0,0,150);
	    $this->Cell(200,20,$rowh['sNombre'],"T",0,'C',0);
		$this->Cell(40,20,"","RT",1);
		$this->SetTextColor(0);
		$this->SetFont('Arial','',12);
		$this->Cell(280,10,"Contrato: ".$rowh['sContrato'],"LBR",0,'C',0);
	$qry2=consulta("*","anexo_pedidos","iFolioPedido=".$Pedido." and sContrato=".$contrato);
	while($rows=mysql_fetch_array($qry2)){
		$qry3=consulta("*","proveedores","sIdProveedor='".$rows['sIdProveedor']."'");
		$rows2=mysql_fetch_array($qry3);
		$this->SetDrawColor(0,0,0);
		$this->SetLineWidth(.1);
		$this->SetFont('Arial','',8);
		$this->Ln();
		$this->Cell(280,4,$rows['sReferencia'],0,1,'R');
		$this->Cell(260,4,"Rev.: ",0,0,'R');
		$this->Cell(20,4,$rows['sRevision'],0,1,'L');
		$this->Cell(260,4,"Fecha: ",0,0,'R');
		$mes=array(1=>'ENE',2=>'FEB',3=>'MAR',4=>'ABR',5=>'MAY',6=>'JUN',7=>'JUL',8=>'AGO',9=>'SEP',10=>'OCT',11=>'NOV',12=>'DIC');
		$m=date('n');
		$this->Cell(20,4,date('d-').$mes[$m].date('-Y'),0,1,'L');
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(20,4,"FACTURAR A: ","TL",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(70,4,$rowh['sNombre'],"T",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(35,4,"PROVEEDOR: ","LT",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(55,4,$rows2['sRazon'],"T",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(100,4,"ORDEN DE COMPRA",1,1,'C',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(20,4,"DIRECCION: ","L",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(70,4,$rowh['sDireccion1'],0,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(35,4,"DIRECCION:","L",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(55,4,$rows2['sDomicilio'],0,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(50,4,"No. Orden de Compra: ",1,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(50,4,$rows['iFolioPedido'],1,1,'C',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(20,4,"COLONIA: ","L",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(70,4,$rowh['sDireccion2'],0,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(35,4,"TELEFONO","L",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(55,4,$rows2['sTelefono'],0,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(50,4,"Contrato",1,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(50,4,$rows['sContrato'],1,1,'C',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(20,4,"C.P.: ","L",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(70,4,$rowh['sDireccion3'],0,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(35,4,"RFC:","L",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(55,4,$rows2['sRfc'],0,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(50,4,"Pagina",1,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(50,4,$this->PageNo().' de {nb}',1,1,'C',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(20,4,"RFC:","L",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(70,4,$rowh['sRfc'],0,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(35,4,"TIEMPO DE ENTREGA:","L",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(55,4,$rows['sTiempoEntrega'],0,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(50,4,"Fecha: ",1,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(50,4,$rows['dIdFecha'],1,1,'C',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(20,4,"E-MAIL:","LB",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(70,4,$rowh['sEmail'],"B",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(35,4,"REFERENCIA:","LB",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(55,4,$rows['sReferencia'],"B",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(50,4,"Elaboro: ",1,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(50,4,$rows['sElaboro'],1,1,'C',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(20,4,"TELEFONO:","LB",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(70,4,$rowh['sTelefono'],"B",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(90,4,"","L",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(50,4,"No. de Requisicion: ",1,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(50,4,$rows['iFolioRequisicion'],1,1,'C',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(20,4,"FAX:","LB",0,'L',1);
		$this->SetFont('Arial','B',6.5);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(70,4,$rowh['sFax'],"B",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(90,4,"","L",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(50,4,"Precios Indicados en: ",1,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(50,4,$rows['sMoneda'],1,1,'C',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(90,4,"","BL",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(90,4,"","LB",0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(250,90,40);
		$this->Cell(50,4,"Numero de Orden: ",1,0,'L',1);
		$this->SetFont('Arial','',8);
		$this->SetTextColor(50);
		$this->SetFillColor(255,255,255);
		$this->Cell(50,4,$rows['sNumeroOrden'],1,0,'C',1);
	}
}
    //Salto de línea
	$this->Ln();
	$w=array('15','15','20','35','20','20','155');
	$this->SetFont('Arial','',8);
		$this->SetTextColor(255);
		$this->SetFillColor(0,0,255);
	$header=array('Partida','Cantidad','Unidad','Codigo','P. UNIT.','P. TOTAL','Descripcion');
		for($i=0;$i<count($header);$i++)
			$this->Cell($w[$i],6,$header[$i],1,0,'C',1);
    $this->Ln(6);
}

//Pie de página
}
//Creación del objeto de la clase heredada
$pdf=new PDF('L','mm','A4');
$pdf->AliasNbPages();
$pdf->SetAutoPageBreak(true,5);
$pdf->AddPage();
$dato=array();
$i=-1;
while($row=mysql_fetch_array($qry)){
	$dato[$i++]=$row['sNumeroActividad'];
	$dato[$i++]=($row['dCantidad']*1);
	$dato[$i++]=$row['sMedida'];
	$dato[$i++]=$row['sIdInsumo'];
	$dato[$i++]=$row['dCosto'];
	$dato[$i++]=($row['dCantidad']*$row['dCosto']);
	$dato[$i++]=$row['mDescripcion'];
	$subT=$subT+($row['dCantidad']*$row['dCosto']);
}
$num_rows=mysql_num_rows($qry);
$pdf->FancyTable($header,$dato,$num_rows);
$pdf->Ln();
$qry=consulta("*","anexo_pedidos","sContrato='".$contrato."' and iFolioPedido=".$Pedido);
$row=mysql_fetch_array($qry);
$pdf->Cell(200,3,"OBSERVACIONES: ","LRT",0,'L',0);
$pdf->Cell(40,3,"SUBTOTAL",1,0,'R',1);
$pdf->Cell(40,3,"$ ".number_format($subT,2),"LRB",1,'R',0);
$pdf->Cell(200,3,$row['mComentarios'],"LR",0,'C',0);
$pdf->Cell(40,3,"15 % DE I.V.A.",1,0,'R',1);
$pdf->Cell(40,3,"$ ".number_format(($subT*.15),2),"LRB",1,'R',0);
$pdf->Cell(200,3,"","LRB",0,'L',0);
$pdf->Cell(40,3,"TOTAL",1,0,'R',1);
$pdf->Cell(40,3,"$ ".number_format(($subT+($subT*.15)),2),"LRB",1,'R',0);
$TexTotal=convertir($subT+($subT*.15));
if($TexTotal){
	$pdf->Cell(280,5,"SON: ","LTR",1,'L',0);
	$pdf->SetTextColor(0);
	$pdf->SetFont('Arial','U',8);
	$pdf->Cell(280,5,$TexTotal,"LR",1,'C',0);
	$pdf->SetTextColor(0);
	$pdf->SetFont('Arial','B',7);
	$pdf->Cell(280,5,"IMPORTE CON LETRA","LBR",0,'C',0);
}
$pdf->Ln();
$qry=consulta("*","anexo_pedidos","sContrato='".$contrato."' and iFolioPedido=".$Pedido);
$pdf->SetTextColor(0);
$pdf->SetFont('Arial','',5);
$pdf->Cell(150,3,"IMPORTANTE: LA PRESENTE ORDEN DE COMPRA ESTA SUJETA A LAS POLITICAS INTERNAS Y CONDICIONES DE ESTA EMPRESA","LTR",0,'L',0);
$pdf->SetFont('Arial','',6);
$pdf->SetTextColor(255);
$pdf->SetFillColor(250,90,40);
$pdf->Cell(32,3,"COSTO",1,0,'C',1);
$pdf->Cell(32,3,"CALIDAD",1,0,'C',1);
$pdf->Cell(32,3,"TIEMPO","LT",0,'C',1);
$pdf->Cell(34,3,"UNICO","LTR",1,'C',1);
$pdf->SetFillColor(255);
$pdf->SetTextColor(0);
$pdf->SetFont('Arial','',5);
$pdf->Cell(150,3,"A) ESTA ORDEN DE COMPRA ESTA SUJETA A CANCELACIONES SI LA MERCANCIA NO ES ENTREGADA EN LA FECHA PROMETIDA","LR",0,'L',0);
$pdf->SetFont('Arial','',6);
$pdf->Cell(32,3,"","LR",0,'C',0);
$pdf->Cell(32,3,"","LR",0,'C',0);
$pdf->SetFillColor(250,90,40);
$pdf->SetTextColor(255);
$pdf->Cell(32,3,"DE","LR",0,'C',1);
$pdf->Cell(34,3,"PROVEEDOR","LR",1,'C',1);
$pdf->SetFont('Arial','',5);
$pdf->SetTextColor(0);
$pdf->SetFillColor(255);
$pdf->Cell(150,3,"B) EL PROVEEDOR DEBERA PROPORCIONAR CERTIFICADO DE GARANTIA DE CALIDAD Y ESPECIFICACIONES TECNICAS","LR",0,'L',0);
$pdf->SetFont('Arial','',6);
$pdf->Cell(32,3,"","LR",0,'C',0);
$pdf->Cell(32,3,"","LR",0,'C',0);
$pdf->SetFillColor(250,90,40);
$pdf->SetTextColor(255);
$pdf->Cell(32,3,"ENTREGA","LRB",0,'C',1);
$pdf->Cell(34,3,"","LRB",1,'C',1);
$pdf->SetFillColor(255);
$pdf->SetTextColor(0);
$pdf->SetFont('Arial','',5);
$pdf->Cell(150,3,"C) REPRESENTACIONES Y DISTRIBUCIONES EVYA SA DE CV SE RESERVA EL DERECHO DE CANCELAR ESTA ORDEN DE COMPRA EN CUALQUIER MOMENTO PREVIO","LR",0,'L',0);
$pdf->SetFont('Arial','',8);
$pdf->Cell(32,3,$row['sCosto'],"LR",0,'C',0);
$pdf->Cell(32,3,$row['sCalidad'],"LR",0,'C',0);
$pdf->Cell(32,3,"","LR",0,'C',0);
$pdf->Cell(34,3,"","LR",1,'C',0);
$pdf->SetFont('Arial','',5);
$pdf->Cell(150,3,"A SU ACEPTACION POR EL PROVEEDOR Y DESPUES DE SU ACEPTACION, SI EL PROVEEDOR ES INCAPAZ DE PROVEER TODO O PARTE DE LOS ARTICULOS DE","LR",0,'L',0);
$pdf->SetFont('Arial','',6);
$pdf->Cell(32,3,"","LR",0,'C',0);
$pdf->Cell(32,3,"","LR",0,'C',0);
$pdf->Cell(32,3,$row['sTiempoEntrega'],"LR",0,'C',0);
$pdf->Cell(34,3,$row['lUnicoProveedor'],"LR",1,'C',0);
$pdf->SetFont('Arial','',5);
$pdf->Cell(150,3,"ACUERDO A LAS CONDICIONES QUE RIGEN ESTA ORDEN DE COMPRA","LRB",0,'L',0);
$pdf->SetFont('Arial','',6);
$pdf->Cell(32,3,"","LRB",0,'C',0);
$pdf->Cell(32,3,"","LRB",0,'C',0);
$pdf->Cell(32,3,"","LRB",0,'C',0);
$pdf->Cell(34,3,"","LRB",1,'C',0);
$pdf->SetFillColor(250,90,40);
$pdf->SetTextColor(255);
$pdf->SetFont('Arial','',7);
$pdf->Cell(150,4,"Costo",1,0,'C',1);
$pdf->Cell(130,4,"Proveedor (Acepto las Condiciones, Instrucciones y Precio de esta O.C.)",1,1,'C',1);
$pdf->Cell(37,4,"LAB",1,0,'C',1);
$pdf->Cell(37,4,"Medios de Transporte",1,0,'C',1);
$pdf->Cell(39,4,"Credito",1,0,'C',1);
$pdf->Cell(37,4,"Forma de Pago",1,0,'C',1);
$pdf->Cell(43,4,"Factura",1,0,'C',1);
$pdf->Cell(43,4,"Nombre",1,0,'C',1);
$pdf->Cell(44,4,"Firma",1,1,'C',1);
$pdf->SetFont('Helvetica','',7);
$pdf->SetFillColor(255);
$pdf->SetTextColor(0);
$pdf->Cell(37,4,$row['sLab'],1,0,'C',1);
$pdf->Cell(37,4,$row['sMedioTransporte'],1,0,'C',1);
$pdf->Cell(39,4,$row['sCredito'],1,0,'C',1);
$pdf->Cell(37,4,$row['sFormaPago'],1,0,'C',1);
$pdf->Cell(43,4,$row['sCosto'],1,0,'C',1);
$pdf->Cell(43,4,"",1,0,'C',1);
$pdf->Cell(44,4,"",1,1,'C',1);
$pdf->SetTextColor(60);
while($row_f=mysql_fetch_array($qry)){
	$pdf->Cell(70,6,"REALIZO","LR",0,'C',0);
	$pdf->Cell(70,6,"AUTORIZO","LR",0,'C',0);
	$pdf->Cell(70,6,"REVISO","LR",0,'C',0);
	$pdf->Cell(70,6,"REVISO","LR",1,'C',0);
	$qry2=consulta("*","usuarios","sIdUsuario='".$row_f['sIdUsuarioCreador']."'");
	$row2=mysql_fetch_array($qry2);
	$pdf->Cell(70,4,$row2['sNombre'],"LR",0,'C',0);
	$qry2=consulta("*","usuarios","sIdUsuario='".$row_f['sIdUsuarioAutoriza']."'");
	$row2=mysql_fetch_array($qry2);
	$pdf->Cell(70,4,$row2['sNombre'],"LR",0,'C',0);
	$qry2=consulta("*","usuarios","sIdUsuario='".$row_f['sIdUsuarioRevisaAdmin']."'");
	$row2=mysql_fetch_array($qry2);
	$pdf->Cell(70,4,$row2['sNombre'],"LR",0,'C',0);
	$qry2=consulta("*","usuarios","sIdUsuario='".$row_f['sIdUsuarioRevisaOper']."'");
	$row2=mysql_fetch_array($qry2);
	$pdf->Cell(70,4,$row2['sNombre'],"LR",1,'C',0);
	$pdf->Cell(70,6,"COMPRAS","LTR",0,'C',0);
	$pdf->Cell(70,6,"GERENCIA DE OPERACIONES","LTR",0,'C',0);
	$pdf->Cell(70,6,"COORDINADOR ADMINISTRATIVO","LTR",0,'C',0);
	$pdf->Cell(70,6,"DIRECCION GENERAL","LTR",1,'C',0);
	$pdf->Cell(70,4,"Puesto, Nombre y Firma","LBR",0,'C',0);
	$pdf->Cell(70,4,"Puesto, Nombre y Firma","LBR",0,'C',0);
	$pdf->Cell(70,4,"Puesto, Nombre y Firma","LBR",0,'C',0);
	$pdf->Cell(70,4,"Puesto, Nombre y Firma","LBR",1,'C',0);
}
$pdf->Output();
?>